"""Type stubs for the compiled extension module ``anamnesis._core``.

The public Python API lives in ``anamnesis/__init__.py``; these are the raw
Rust-backed primitives it wraps. They take plain ``list[float]`` and return plain
tuples (the package wraps them in namedtuples).
"""
from typing import List, Optional, Tuple

__version__: str

def brier(probs: List[float], outcomes: List[float]) -> Optional[float]: ...
def brier_weighted(
    probs: List[float], outcomes: List[float], weights: List[float]
) -> Optional[float]: ...
def log_score(probs: List[float], outcomes: List[float], eps: float = ...) -> Optional[float]: ...
def base_rate(probs: List[float], outcomes: List[float]) -> Optional[float]: ...
def decompose(
    probs: List[float], outcomes: List[float]
) -> Optional[Tuple[float, float, float, float]]: ...
def skill_score(probs: List[float], outcomes: List[float]) -> Optional[float]: ...
def auc(probs: List[float], outcomes: List[float]) -> Optional[float]: ...
def overconfidence(
    probs: List[float], outcomes: List[float]
) -> Optional[Tuple[float, float, float]]: ...
def directional_bias(probs: List[float], outcomes: List[float]) -> Optional[float]: ...
def calibration_curve(
    probs: List[float], outcomes: List[float], n_bins: int = ...
) -> List[Tuple[float, float, int, float, Optional[float]]]: ...
def winkler(low: float, high: float, level: float, value: float) -> float: ...
def coverage(
    lows: List[float], highs: List[float], levels: List[float], values: List[float]
) -> Optional[float]: ...
def wilson_interval(
    successes: float, n: int, z: float = ...
) -> Optional[Tuple[float, float]]: ...
def shrink_toward(successes: float, n: int, prior_mean: float, strength: float) -> float: ...
def calibration_eprocess(probs: List[float], outcomes: List[float]) -> Optional[float]: ...
def eprocess_pvalue(e: float) -> float: ...
def fit_recalibration(
    probs: List[float], outcomes: List[float], ridge: float = ...
) -> Optional[Tuple[float, float, int]]: ...
def recalibration_apply(a: float, b: float, p: float) -> float: ...
def brier_ci_bootstrap(
    probs: List[float], outcomes: List[float], level: float = ..., resamples: int = ..., seed: int = ...
) -> Optional[Tuple[float, float]]: ...
def ewma_brier(probs: List[float], outcomes: List[float], half_life: float = ...) -> Optional[float]: ...
def distinct_forecasts(probs: List[float]) -> int: ...
def risk_coverage_summary(
    probs: List[float], outcomes: List[float]
) -> Optional[Tuple[float, float, float]]: ...
def risk_coverage_curve(
    probs: List[float], outcomes: List[float]
) -> List[Tuple[float, float]]: ...
def dialectical_mean(p1: float, p2: float) -> float: ...
